### PR TITLE
Sanitizes user input for account string

### LINKED ISSUE #233: Strip user-supplied account string parameter
There can be issues with the accounting database when a user begins the account string with a Space char.

Ensure that a string strip is performed on user input for account string, and probably the rest of the user params.

### PR DESCRIPTION
**Pull request by nickjer**
Fixes #233

### CODE REVIEW

**Comment by brianmcmichael** [comment]
You'd only need to do:

```
def account
    job_attrs[:account].try(:strip) unless job_attrs[:account].blank?
end
```

since

```
irb(main):003:0> "   ".blank?
=> true
```

**Comment by nickjer** [comment]
I'd actually have to do:

```ruby
def account
    job_attrs[:account].strip unless job_attrs[:account].try(:strip).blank?
end
```

since `job_attrs[:account] == "    "` would submit with `accounting_id: ""`, which does `qsub -A ''`.

**Comment by brianmcmichael** [comment]
No, see my previous comment.

When `job_attrs[:account] == " "`,  `job_attrs[:account].blank?` evaluates to `true`, so `account()` returns `nil`.

**Comment by nickjer** [comment]
Ah I didn't notice that. Is this true for all whitespace?

**Comment by nickjer** [comment]
Ah, I was reading the wrong `#blank?` in ActiveSupport. Turns out `String` has its own `#blank?` and not to be confused with `Object`.

https://github.com/rails/rails/blob/3fc47f4d82175c3f32dab6177685ae24f485c7b1/activesupport/lib/active_support/core_ext/object/blank.rb#L103-L124

**Comment by nickjer** [comment]
That makes life easier then. So I can get away with just:

```ruby
def account
    job_attrs[:account].strip unless job_attrs[:account].blank?
end
```

**Pull request merged**
