### PR TITLE
Add a view helper to display the cluster title instead of the titleized id

### LINKED ISSUE #222: Not displaying correct cluster title
Similar to https://github.com/OSC/ood-activejobs/issues/122

I noticed during the PSC demo that the titleized id was displaying instead of the metadata title.

### PR DESCRIPTION
**Pull request by brianmcmichael**
Resolves #222 

* Display a cluster's metadata title instead of titlized id.

### CODE REVIEW

**Comment by nickjer** [comment]
Not too familiar with the specifics of this code, but have you tested this for the case that a workflow specifies a cluster that doesn't exist in the cluster config? I believe your `cluster_title` helper will return `nil`.

You should also check it for templates with an invalid cluster id as well.

**Comment by brianmcmichael** [comment]
`cluster_title` is only used in the view. So `nil` is fine here.

**Comment by nickjer** [comment]
Right, but it can't hurt to run through a test and make sure it doesn't break anything. Also, maybe a more descriptive title would be better if the cluster doesn't exist like "Invalid Cluster".

**Comment by brianmcmichael** [comment]
When it's `nil`, it just doesn't render anything.

nil_title

**Comment by ericfranz** [comment]
I'm okay with this, but there is a merge conflict with CHANGELOG.md. Fix and we can merge.

**Comment by brianmcmichael** [comment]
Resolved

**Pull request merged**
