### PR TITLE
Allow for relative paths in template creation

### LINKED ISSUE #205: Allow template path to be specified with `~user` format
It was stated that the template path cannot handle the case:

```
~user/path/to/template
```

and instead it must be specified as:

```
/users/PZZ4385/user/path/to/template
```

It may be best to allow both options.

### PR DESCRIPTION
**Pull request by brianmcmichael**
Fixes #205

### CODE REVIEW

**Comment by nickjer** [comment]
Just a suggestion, but you could also use the Pathname object that you originally created...

```ruby
@path = Pathname.new(path).expand_path
```

**Comment by brianmcmichael** [comment]
I will do that since it looks cleaner. I'll still need to keep the rescue because `Pathname#expand_path` throws an ArgumentError if the path doesn't exist.

**Comment by nickjer** [comment]
Does it?

```
[1] pry(main)> Pathname.new("/a/b/c/d").expand_path
=> #<Pathname:/a/b/c/d>
[2] pry(main)> Pathname.new("~jnicklas/b/c/d").expand_path
=> #<Pathname:/users/appl/jnicklas/b/c/d>
```

**Comment by brianmcmichael** [comment]
We're expecting user input at this point so any input is possible.

```
irb(main):002:0* p = Pathname.new "~/lasdf"
=> #<Pathname:~/lasdf>
irb(main):003:0> p.expand_path
=> #<Pathname:/users/appl/bmcmichael/lasdf>
irb(main):004:0> p = Pathname.new "~lasdf"
=> #<Pathname:~lasdf>
irb(main):005:0> p.expand_path
ArgumentError: user lasdf doesn't exist
        from (irb):5:in `expand_path'
        from (irb):5:in `expand_path'
        from (irb):5
        from /users/appl/bmcmichael/ondemand/dev/myjobs/vendor/bundle/ruby/gems/railties-4.1.15/lib/rails/com
mands/console.rb:90:in `start'
        from /users/appl/bmcmichael/ondemand/dev/myjobs/vendor/bundle/ruby/gems/railties-4.1.15/lib/rails/com
mands/console.rb:9:in `start'
        from /users/appl/bmcmichael/ondemand/dev/myjobs/vendor/bundle/ruby/gems/railties-4.1.15/lib/rails/com
mands/commands_tasks.rb:69:in `console'
        from /users/appl/bmcmichael/ondemand/dev/myjobs/vendor/bundle/ruby/gems/railties-4.1.15/lib/rails/com
mands/commands_tasks.rb:40:in `run_command!'
        from /users/appl/bmcmichael/ondemand/dev/myjobs/vendor/bundle/ruby/gems/railties-4.1.15/lib/rails/com
mands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by nickjer** [comment]
Right, if the user doesn't exist then it throws an error. You should rescue from that and display an error message to the user that the user he specified doesn't exist.

**Comment by brianmcmichael** [comment]
Error handling for this is already done elsewhere.

**Comment by brianmcmichael** [comment]
Specifically, in the controller, at https://github.com/OSC/ood-myjobs/blob/b5608bec3ecac7edc0359e292a779f1e26ed2b4f/app/controllers/templates_controller.rb#L43

**Comment by nickjer** [comment]
Thanks for the link, that helps.

This is probably a separate issue but I notice you do a lot of boolean checks in the controller and if one of them returns an error you still continue on.

For example:

```ruby
unless template_location.exist? then @template.errors.add(:path, "does not exist.") end
```

(note: this could be simplified with `@template.errors.add(:path, "does not exist.") unless template_location.exist?`)

so we know the directory doesn't exist in the file system. Yet in the very next line:

```ruby
copy_safe, error = Filesystem.new.validate_path_is_copy_safe(template_location.to_s)
```

we start to call system commands on that non-existant directory. Your code is probably resilient enough for this, but it can lead to crashes in the future if you stick code in there that expects a directory to exist already.

If you ever resolve that, then it would allow you more flexibility to capture errors earlier in the chain such as invalid users when expanding out ~.

**Pull request merged**
